blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://github.com/padrewin/NetStat/discussions
    about: Use GitHub discussions feature for questions
  - name: ğŸ‘¾ Discord server
    url: https://discord.colddev.dev
    about: Keep in touch in Discord server
